//! CTAP2 PIN protocol v1/v2 implementation (US-314).
//!
//! Implements the ClientPIN command: getRetries, getKeyAgreement, setPIN,
//! changePIN, getPinToken / getPinUvAuthToken.  The PIN protocol derives a
//! shared secret through ECDH on P-256, then uses HKDF to obtain an HMAC key
//! and an AES-256-CBC encryption key.

use crate::cbor::{self, Value};
use crate::crypto;
use crate::keystore::{CosePublicKey, Keystore};
use crate::FidoError;
use p256::SecretKey;

/// Result of processing a client PIN command.
pub struct PinProtocolOutput {
    pub response: ClientPinResponse,
    /// Raw (unencrypted) 32-byte pin token, if a new one was generated by
    /// getPinToken.  The caller stores this for later pinUvAuthParam
    /// verification in makeCredential / getAssertion.
    pub raw_pin_token: Option<Vec<u8>>,
}

/// Client PIN response fields (encoded as a CBOR map by
/// [`encode_client_pin_response`]).
#[derive(Debug, Clone, PartialEq)]
pub struct ClientPinResponse {
    /// Key agreement (COSE key) at CBOR key 0x01.
    pub key_agreement: Option<CosePublicKey>,
    /// Encrypted pin token at CBOR key 0x02.
    pub pin_token: Option<Vec<u8>>,
    /// Retry count at CBOR key 0x03.
    pub retries: Option<u8>,
    /// Power-cycle state at CBOR key 0x04.
    pub power_cycle_state: bool,
    /// UV retry count at CBOR key 0x05.
    pub uv_retries: Option<u8>,
}

/// Parsed fields from the client PIN CBOR map.
struct ClientPinParams {
    pin_uv_auth_protocol: u8,
    subcommand: u8,
    key_agreement: Option<PublicKey>,
    pin_uv_auth_param: Option<Vec<u8>>,
    new_pin_enc: Option<Vec<u8>>,
    pin_hash_enc: Option<Vec<u8>>,
    permissions: Option<u8>,
}

use p256::PublicKey;
const MAX_PIN_RETRIES: u8 = 8;

/// PIN protocol handler.  Borrows the keystore mutably and the persistent
/// ECDH key agreement key (`hkey`) immutably.
pub struct PinProtocol<'a> {
    keystore: &'a mut dyn Keystore,
    hkey_secret: &'a SecretKey,
}

impl<'a> PinProtocol<'a> {
    pub fn new(keystore: &'a mut dyn Keystore, hkey: &'a SecretKey) -> Self {
        Self {
            keystore,
            hkey_secret: hkey,
        }
    }

    /// US-910: replace a legacy unsalted verifier with the salted, stretched
    /// format. Called only after a *successful* verification, so the same
    /// PIN re-verifies under the new format; a wrong PIN can never reach
    /// here and therefore never migrates the record.
    fn migrate_legacy_pin_verifier(&mut self, verified_candidate: &[u8; 16]) {
        let legacy = {
            let s = self.keystore.get_pin_state();
            s.pin_verifier_format != crypto::PIN_VERIFIER_FORMAT_STRETCHED
        };
        if !legacy {
            return;
        }
        let salt = crypto::random_bytes::<16>();
        let (verifier, iter) = crypto::pin_verifier_upgrade(verified_candidate, &salt);
        {
            let s = self.keystore.get_pin_state_mut();
            s.pin_hash = Some(verifier);
            s.pin_verifier_format = crypto::PIN_VERIFIER_FORMAT_STRETCHED;
            s.pin_salt = Some(salt);
            s.pin_iter = iter;
        }
        let _ = self.keystore.save_pin_state();
    }

    /// Process a client PIN command (raw CBOR map).
    pub fn process(&mut self, data: &[u8]) -> Result<PinProtocolOutput, FidoError> {
        if data.is_empty() {
            return Err(FidoError::MissingParameter);
        }

        let (value, _) = cbor::decode(data).map_err(|_| FidoError::Cbor)?;
        let params = parse_client_pin_params(&value)?;

        if params.pin_uv_auth_protocol != 1 && params.pin_uv_auth_protocol != 2 {
            return Err(FidoError::InvalidParameter);
        }

        if params.subcommand == 0 {
            return Err(FidoError::MissingParameter);
        }

        match params.subcommand {
            0x01 => self.get_retries(params),
            0x02 => self.get_key_agreement(params),
            0x03 => self.set_pin(params),
            0x04 => self.change_pin(params),
            0x05 | 0x09 => self.get_pin_token(params),
            0x06 => self.get_pin_token_uv(params),
            0x07 => self.get_uv_retries(),
            _ => Err(FidoError::InvalidParameter),
        }
    }

    // -- Shared ECDH helper ------------------------------------------------

    /// Derive the 64-byte shared secret (v2) or 32-byte (v1) from the client's
    /// public key and the persistent hkey.
    fn derive_shared_secret(&self, protocol: u8, client_pub: &PublicKey) -> [u8; 64] {
        let raw = crypto::ecdh_shared_secret(self.hkey_secret, client_pub);
        if protocol == 1 {
            // v1: hmac_key = enc_key = SHA256(raw)
            let k = crypto::derive_shared_secret_v1(&raw);
            let mut shared = [0u8; 64];
            shared[..32].copy_from_slice(&k);
            shared[32..].copy_from_slice(&k);
            shared
        } else {
            crypto::derive_shared_secret_v2(&raw)
        }
    }

    fn hmac_key(shared: &[u8; 64]) -> [u8; 32] {
        crypto::hmac_key_from_v2(shared)
    }
    fn enc_key(shared: &[u8; 64]) -> [u8; 32] {
        crypto::enc_key_from_v2(shared)
    }

    // -- Subcommands -------------------------------------------------------

    fn get_retries(&self, _params: ClientPinParams) -> Result<PinProtocolOutput, FidoError> {
        let state = self.keystore.get_pin_state();
        let retries = state.retries;
        let power_cycle_state = state.needs_power_cycle || state.blocked;
        Ok(PinProtocolOutput {
            response: ClientPinResponse {
                key_agreement: None,
                pin_token: None,
                retries: Some(retries),
                power_cycle_state,
                uv_retries: None,
            },
            raw_pin_token: None,
        })
    }

    /// getUVRetries (0x07). US-1513: the budget was a hard-coded 3 that no test
    /// could observe. It now tracks the same `auth_failures` counter the
    /// latch in `note_pin_auth_failure` uses, and reports the durable
    /// lockout as `powerCycleState` — the same pair of keys CTAP2.1 §6.5.5.4
    /// defines and the device twin writes at `device_core.rs:1558`.
    fn get_uv_retries(&self) -> Result<PinProtocolOutput, FidoError> {
        let state = self.keystore.get_pin_state();
        Ok(PinProtocolOutput {
            response: ClientPinResponse {
                key_agreement: None,
                pin_token: None,
                retries: None,
                power_cycle_state: state.blocked || state.needs_power_cycle,
                uv_retries: Some(crate::ctap2::uv_retries(state.auth_failures)),
            },
            raw_pin_token: None,
        })
    }

    fn get_key_agreement(&self, _params: ClientPinParams) -> Result<PinProtocolOutput, FidoError> {
        let public = self.hkey_secret.public_key();
        let bytes = crypto::public_key_bytes(&public);

        let mut x = [0u8; 32];
        let mut y = [0u8; 32];
        x.copy_from_slice(&bytes[1..33]);
        y.copy_from_slice(&bytes[33..65]);

        let cose_key = CosePublicKey {
            kty: 2,
            alg: crate::COSE_ALG_ECDH_ES_HKDF_256,
            crv: Some(1),
            x: Some(x.to_vec()),
            y: Some(y.to_vec()),
            n: None,
            e: None,
            okp_key: None,
        };

        Ok(PinProtocolOutput {
            response: ClientPinResponse {
                key_agreement: Some(cose_key),
                pin_token: None,
                retries: None,
                power_cycle_state: false,
                uv_retries: None,
            },
            raw_pin_token: None,
        })
    }

    fn set_pin(&mut self, params: ClientPinParams) -> Result<PinProtocolOutput, FidoError> {
        let state = self.keystore.get_pin_state();
        if state.pin_hash.is_some() {
            return Err(FidoError::NotAllowed);
        }

        let client_pub = params.key_agreement.ok_or(FidoError::MissingParameter)?;
        let new_pin_enc = params.new_pin_enc.ok_or(FidoError::MissingParameter)?;
        let pin_uv_auth_param =
            params.pin_uv_auth_param.ok_or(FidoError::MissingParameter)?;

        let protocol = params.pin_uv_auth_protocol;
        let shared = self.derive_shared_secret(protocol, &client_pub);
        let hmac_key = Self::hmac_key(&shared);
        let enc_key = Self::enc_key(&shared);

        // Verify PIN auth
        if !crypto::pin_verify_auth(protocol, &hmac_key, &new_pin_enc, &pin_uv_auth_param) {
            return Err(FidoError::PinAuthInvalid);
        }

        // Decrypt new PIN (padded to 64 bytes, zero-padded buffer in C)
        let mut decoded =
            crypto::pin_decrypt(protocol, &enc_key, &new_pin_enc).ok_or(FidoError::PinAuthInvalid)?;

        // Check length constraints (matching C: new_pin_plain_len > 64 or padded[63] != 0)
        let plain_len = decoded.len();
        if plain_len > 64 {
            return Err(FidoError::PinPolicyViolation);
        }
        while decoded.len() < 64 {
            decoded.push(0u8);
        }
        if decoded[63] != 0 {
            return Err(FidoError::PinPolicyViolation);
        }

        // Find PIN byte length (null terminator)
        let pin_byte_len = decoded.iter().position(|&b| b == 0).unwrap_or(64);

        // All bytes after the null terminator must be zero (CTAP2.1 §6.5.5.2).
        if decoded[pin_byte_len..].iter().any(|&b| b != 0) {
            return Err(FidoError::PinPolicyViolation);
        }

        // Count codepoints
        let codepoints = count_codepoints(&decoded[..pin_byte_len]);

        // Check minimum PIN length
        let min_pin = self.keystore.get_pin_state().min_pin_length;
        if codepoints < min_pin as usize {
            return Err(FidoError::PinPolicyViolation);
        }

        // Store the salted, stretched verifier (US-910). set/change-PIN
        // always emit the new format atomically (single save below).
        let pin_hash = crypto::pin_hash(&decoded[..pin_byte_len]);
        let salt = crypto::random_bytes::<16>();
        let (verifier, iter) = crypto::pin_verifier_upgrade(&pin_hash, &salt);
        {
            let state = self.keystore.get_pin_state_mut();
            state.pin_hash = Some(verifier);
            state.pin_verifier_format = crypto::PIN_VERIFIER_FORMAT_STRETCHED;
            state.pin_salt = Some(salt);
            state.pin_iter = iter;
            state.retries = MAX_PIN_RETRIES;
            state.blocked = false;
            state.needs_power_cycle = false;
            state.new_pin_mismatches = 0;
        }
        self.keystore.save_pin_state().map_err(|_| FidoError::Internal)?;

        Ok(PinProtocolOutput {
            response: ClientPinResponse {
                key_agreement: None,
                pin_token: None,
                retries: Some(MAX_PIN_RETRIES),
                power_cycle_state: false,
                uv_retries: None,
            },
            raw_pin_token: None,
        })
    }

    fn change_pin(&mut self, params: ClientPinParams) -> Result<PinProtocolOutput, FidoError> {
        let state = self.keystore.get_pin_state();
        if state.pin_hash.is_none() {
            return Err(FidoError::PinNotSet);
        }
        if state.retries == 0 {
            return Err(FidoError::PinBlocked);
        }

        let client_pub = params.key_agreement.ok_or(FidoError::MissingParameter)?;
        let pin_hash_enc = params.pin_hash_enc.ok_or(FidoError::MissingParameter)?;
        let new_pin_enc = params.new_pin_enc.ok_or(FidoError::MissingParameter)?;
        let pin_uv_auth_param =
            params.pin_uv_auth_param.ok_or(FidoError::MissingParameter)?;

        let protocol = params.pin_uv_auth_protocol;
        let shared = self.derive_shared_secret(protocol, &client_pub);
        let hmac_key = Self::hmac_key(&shared);
        let enc_key = Self::enc_key(&shared);

        // Verify HMAC over (newPinEnc || pinHashEnc)
        let mut auth_data = Vec::new();
        auth_data.extend_from_slice(&new_pin_enc);
        auth_data.extend_from_slice(&pin_hash_enc);
        if !crypto::pin_verify_auth(protocol, &hmac_key, &auth_data, &pin_uv_auth_param) {
            return Err(FidoError::PinAuthInvalid);
        }

        // Decrypt pinHashEnc → old pin hash (16 bytes)
        let old_pin_hash =
            crypto::pin_decrypt(protocol, &enc_key, &pin_hash_enc)
                .ok_or(FidoError::PinAuthInvalid)?;
        if old_pin_hash.len() != 16 {
            return Err(FidoError::PinAuthInvalid);
        }

        // Decrement retries (matching C behavior)
        {
            let s = self.keystore.get_pin_state_mut();
            if s.retries > 0 {
                s.retries -= 1;
            }
        }
        self.keystore.save_pin_state().map_err(|_| FidoError::Internal)?;

        // Compare with stored pin hash (format-aware, US-910).
        let (stored, fmt, salt, iter) = {
            let s = self.keystore.get_pin_state();
            (
                s.pin_hash.ok_or(FidoError::PinNotSet)?,
                s.pin_verifier_format,
                s.pin_salt,
                s.pin_iter,
            )
        };
        debug_assert_eq!(old_pin_hash.len(), 16);
        let old_hash_arr: [u8; 16] = old_pin_hash[..16].try_into().unwrap();

        if !crypto::pin_verifier_matches(&stored, fmt, salt.as_ref(), iter, &old_hash_arr) {
            // Mismatch — lockout handling
            let s = self.keystore.get_pin_state_mut();
            if s.retries == 0 {
                return Err(FidoError::PinBlocked);
            }
            s.new_pin_mismatches += 1;
            if s.blocked || s.new_pin_mismatches >= 3 {
                s.blocked = true;
                s.needs_power_cycle = true;
                let _ = self.keystore.save_pin_state();
                return Err(FidoError::PinAuthBlocked);
            }
            let _ = self.keystore.save_pin_state();
            return Err(FidoError::PinInvalid);
        }

        // US-910: successful verification of a legacy record migrates it
        // (wrong PINs never reach here, so they cannot migrate).
        self.migrate_legacy_pin_verifier(&old_hash_arr);

        // PIN matches — validate and store new PIN
        let mut decoded_new = crypto::pin_decrypt(protocol, &enc_key, &new_pin_enc)
            .ok_or(FidoError::PinAuthInvalid)?;

        let plain_len = decoded_new.len();
        if plain_len > 64 {
            return Err(FidoError::PinPolicyViolation);
        }
        while decoded_new.len() < 64 {
            decoded_new.push(0u8);
        }
        if decoded_new[63] != 0 {
            return Err(FidoError::PinPolicyViolation);
        }

        let pin_byte_len = decoded_new.iter().position(|&b| b == 0).unwrap_or(64);

        // All bytes after the null terminator must be zero (CTAP2.1 §6.5.5.2).
        if decoded_new[pin_byte_len..].iter().any(|&b| b != 0) {
            return Err(FidoError::PinPolicyViolation);
        }

        let codepoints = count_codepoints(&decoded_new[..pin_byte_len]);

        let min_pin = self.keystore.get_pin_state().min_pin_length;
        if codepoints < min_pin as usize {
            return Err(FidoError::PinPolicyViolation);
        }

        let new_pin_hash = crypto::pin_hash(&decoded_new[..pin_byte_len]);
        let salt = crypto::random_bytes::<16>();
        let (verifier, iter) = crypto::pin_verifier_upgrade(&new_pin_hash, &salt);
        {
            let s = self.keystore.get_pin_state_mut();
            s.pin_hash = Some(verifier);
            s.pin_verifier_format = crypto::PIN_VERIFIER_FORMAT_STRETCHED;
            s.pin_salt = Some(salt);
            s.pin_iter = iter;
            s.retries = MAX_PIN_RETRIES;
            s.blocked = false;
            s.needs_power_cycle = false;
            s.new_pin_mismatches = 0;
            // A successful changePIN clears the forced-change flag
            // (CTAP2.1 §6.5.5.3).
            s.force_pin_change = false;
        }
        self.keystore.save_pin_state().map_err(|_| FidoError::Internal)?;

        Ok(PinProtocolOutput {
            response: ClientPinResponse {
                key_agreement: None,
                pin_token: None,
                retries: Some(MAX_PIN_RETRIES),
                power_cycle_state: false,
                uv_retries: None,
            },
            raw_pin_token: None,
        })
    }

    fn get_pin_token(&mut self, params: ClientPinParams) -> Result<PinProtocolOutput, FidoError> {
        // FX-405: getPinUvAuthTokenUsingPinWithPermissions (0x09) requires the
        // permissions parameter (CTAP2.1 §6.5.5.4), and the bioEnroll
        // permission requires PIN protocol v2 semantics.
        //
        // Deviations from the FX-405 findings text, resolved in favor of the
        // spec and the python-fido2 client (house rule: the suite is the
        // gate and cannot be edited):
        // - pinUvAuthParam == pinUvAuth(hmac_key, "") is specified for
        //   getPinUvAuthTokenUsingUvWithPermissions (0x0A), not 0x09 —
        //   python-fido2 never sends pinUvAuthParam on 0x09; PIN knowledge
        //   is proven by decrypting pinHashEnc.
        // - An rpId is not mandatory at mint time for the be/lbf/acfg
        //   permissions (the suite requests largeBlobWrite without one);
        //   instead the rpId is bound to the token and enforced at
        //   makeCredential/getAssertion time.
        if params.subcommand == 0x09 {
            let permissions = params.permissions.ok_or(FidoError::MissingParameter)?;
            if permissions & 0x08 != 0 && params.pin_uv_auth_protocol != 2 {
                return Err(FidoError::PinAuthInvalid);
            }
        }
        let (pin_set, force_pin_change) = {
            let state = self.keystore.get_pin_state();
            (state.pin_hash.is_some(), state.force_pin_change)
        };
        if !pin_set {
            return Err(FidoError::PinNotSet);
        }
        if self.keystore.get_pin_state().retries == 0 {
            return Err(FidoError::PinBlocked);
        }

        let client_pub = params.key_agreement.ok_or(FidoError::MissingParameter)?;
        let pin_hash_enc = params.pin_hash_enc.ok_or(FidoError::MissingParameter)?;

        let protocol = params.pin_uv_auth_protocol;
        let shared = self.derive_shared_secret(protocol, &client_pub);
        let enc_key = Self::enc_key(&shared);

        // Decrypt pinHashEnc → 16-byte PIN hash candidate.
        // NOTE: the legacy getPinToken (subcommand 0x05) does NOT require or
        // verify pinUVAuthParam — it relies solely on encryption for
        // confidentiality (matches the C reference cbor_client_pin.c).
        let decoded =
            crypto::pin_decrypt(protocol, &enc_key, &pin_hash_enc)
                .ok_or(FidoError::PinAuthInvalid)?;
        if decoded.len() < 16 {
            return Err(FidoError::PinAuthInvalid);
        }

        // Decrement retries (matching C — done before comparison)
        {
            let s = self.keystore.get_pin_state_mut();
            if s.retries > 0 {
                s.retries -= 1;
            }
        }
        self.keystore.save_pin_state().map_err(|_| FidoError::Internal)?;

        let (stored, fmt, salt, iter) = {
            let s = self.keystore.get_pin_state();
            (
                s.pin_hash.ok_or(FidoError::PinNotSet)?,
                s.pin_verifier_format,
                s.pin_salt,
                s.pin_iter,
            )
        };

        debug_assert!(decoded.len() >= 16, "AES-CBC success implies a full block");
        let decoded_hash: [u8; 16] = decoded[..16].try_into().unwrap();

        if !crypto::pin_verifier_matches(&stored, fmt, salt.as_ref(), iter, &decoded_hash) {
            // Mismatch — lockout handling
            let s = self.keystore.get_pin_state_mut();
            if s.retries == 0 {
                return Err(FidoError::PinBlocked);
            }
            s.new_pin_mismatches += 1;
            if s.blocked || s.new_pin_mismatches >= 3 {
                s.blocked = true;
                s.needs_power_cycle = true;
                let _ = self.keystore.save_pin_state();
                return Err(FidoError::PinAuthBlocked);
            }
            let _ = self.keystore.save_pin_state();
            return Err(FidoError::PinInvalid);
        }

        // US-910: successful verification of a legacy record migrates it
        // (wrong PINs never reach here, so they cannot migrate).
        self.migrate_legacy_pin_verifier(&decoded_hash);

        // PIN matches — clear the durable latch here (US-909): a correct PIN
        // is the only thing that lifts the 3-strike lockout now that it
        // survives reconnects.
        //
        // A correct PIN is still rejected with PIN_INVALID while a forced
        // PIN change is pending; the client must changePIN first
        // (CTAP2.1 §6.5.5.4).
        if force_pin_change {
            return Err(FidoError::PinInvalid);
        }

        // Reset counters, generate pin token
        let s = self.keystore.get_pin_state_mut();
        s.retries = MAX_PIN_RETRIES;
        s.blocked = false;
        s.needs_power_cycle = false;
        s.new_pin_mismatches = 0;
        let _ = self.keystore.save_pin_state();

        // Generate raw pin token (32 random bytes)
        let pin_token = crypto::random_vec(32);

        // Encrypt pin token for the response
        let encrypted_token = crypto::pin_encrypt(protocol, &enc_key, &pin_token);

        Ok(PinProtocolOutput {
            response: ClientPinResponse {
                key_agreement: None,
                pin_token: Some(encrypted_token),
                retries: Some(MAX_PIN_RETRIES),
                power_cycle_state: false,
                uv_retries: None,
            },
            raw_pin_token: Some(pin_token),
        })
    }

    /// `getPinUvAuthTokenUsingUvWithPermissions` (sub-command `0x06`).
    ///
    /// The no-PIN leg of the token exchange. A client whose key has no PIN
    /// still needs a pinUvAuthToken before it may call credentialManagement
    /// — without this sub-command there is no way to obtain one, and the
    /// resident-credential screens (Slots, Passkeys) never resolve. The
    /// device twin gates it on a user-presence grant; the host twin has no
    /// presence probe and auto-acks, matching the rest of the host stack
    /// (US-908).
    fn get_pin_token_uv(&mut self, params: ClientPinParams) -> Result<PinProtocolOutput, FidoError> {
        // US-1512: mirror of the lockout gate the device twin puts in front
        // of the same sub-command. A durable lockout refuses every PIN leg,
        // so the one route that needs no PIN must refuse too — otherwise this
        // twin mints a token the board would not.
        let state = self.keystore.get_pin_state();
        if state.blocked || state.needs_power_cycle {
            return Err(FidoError::PinAuthBlocked);
        }
        let permissions = params.permissions.ok_or(FidoError::MissingParameter)?;
        if permissions & 0x08 != 0 && params.pin_uv_auth_protocol != 2 {
            return Err(FidoError::PinAuthInvalid);
        }
        let client_pub = params.key_agreement.ok_or(FidoError::MissingParameter)?;
        let protocol = params.pin_uv_auth_protocol;
        let shared = self.derive_shared_secret(protocol, &client_pub);
        let mut enc_key = [0u8; 32];
        enc_key.copy_from_slice(&shared[32..]);
        let pin_token = crypto::random_vec(32);
        let encrypted_token = crypto::pin_encrypt(protocol, &enc_key, &pin_token);
        Ok(PinProtocolOutput {
            response: ClientPinResponse {
                key_agreement: None,
                pin_token: Some(encrypted_token),
                retries: None,
                power_cycle_state: false,
                uv_retries: None,
            },
            raw_pin_token: Some(pin_token),
        })
    }
}

// ------------------------------------------------------------------
// CBOR parsing helpers
// ------------------------------------------------------------------

fn parse_client_pin_params(value: &Value) -> Result<ClientPinParams, FidoError> {
    let map = match value {
        Value::M(m) => m,
        _ => return Err(FidoError::Cbor),
    };

    let get_uint = |key: u64| -> Option<u64> {
        map.iter()
            .find(|(k, _)| matches!(k, Value::U(u) if *u == key))
            .and_then(|(_, v)| match v {
                Value::U(u) => Some(*u),
                Value::N(n) => Some((-*n - 1) as u64),
                _ => None,
            })
    };

    let get_bytes = |key: u64| -> Option<Vec<u8>> {
        map.iter()
            .find(|(k, _)| matches!(k, Value::U(u) if *u == key))
            .and_then(|(_, v)| match v {
                Value::B(b) => Some(b.clone()),
                _ => None,
            })
    };

    let get_text = |key: u64| -> Option<String> {
        map.iter()
            .find(|(k, _)| matches!(k, Value::U(u) if *u == key))
            .and_then(|(_, v)| match v {
                Value::T(s) => Some(s.clone()),
                _ => None,
            })
    };

    let get_map = |key: u64| -> Option<&Vec<(Value, Value)>> {
        map.iter()
            .find(|(k, _)| matches!(k, Value::U(u) if *u == key))
            .and_then(|(_, v)| match v {
                Value::M(m) => Some(m),
                _ => None,
            })
    };

    let pin_uv_auth_protocol = get_uint(0x01).unwrap_or(0) as u8;
    let subcommand = get_uint(0x02).unwrap_or(0) as u8;

    let key_agreement = get_map(0x03).and_then(|m| parse_cose_key_map(m));
    let pin_uv_auth_param = get_bytes(0x04);
    let new_pin_enc = get_bytes(0x05);
    let pin_hash_enc = get_bytes(0x06);
    let permissions = get_uint(0x09).map(|v| v as u8);
    let _ = get_text(0x0A);

    Ok(ClientPinParams {
        pin_uv_auth_protocol,
        subcommand,
        key_agreement,
        pin_uv_auth_param,
        new_pin_enc,
        pin_hash_enc,
        permissions,
    })
}

fn parse_cose_key_map(map: &[(Value, Value)]) -> Option<PublicKey> {
    // Labels are looked up by value, never by position, so map order is
    // irrelevant; the `alg` label (3) is never read at all. Both are
    // deliberate — see the US-120 rationale at `crate::COSE_ALG_ES256`.
    let get_bytes = |key: i64| -> Option<Vec<u8>> {
        map.iter().find(|(k, _)| match k {
            Value::U(u) => *u as i64 == key,
            Value::N(n) => *n == key,
            _ => false,
        }).and_then(|(_, v)| match v {
            Value::B(b) => Some(b.clone()),
            _ => None,
        })
    };

    let x = get_bytes(-2)?;
    let y = get_bytes(-3)?;
    crypto::parse_cose_ec2_p256(&x, &y)
}

/// Count Unicode codepoints (non-continuation bytes in UTF-8).
fn count_codepoints(data: &[u8]) -> usize {
    data.iter().filter(|&&b| (b & 0xC0) != 0x80).count()
}

// ------------------------------------------------------------------
// CBOR encoding of the response
// ------------------------------------------------------------------

/// Encode a client PIN response to CBOR.
pub fn encode_client_pin_response(response: &ClientPinResponse) -> Vec<u8> {
    let mut map = vec![];

    if let Some(ref key) = response.key_agreement {
        let cose_key = Value::M(vec![
            (Value::U(1), Value::U(2)),
            (Value::U(3), Value::N(key.alg as i64)),
            (Value::N(-1), Value::U(key.crv.unwrap_or(1) as u64)),
            (Value::N(-2), Value::B(key.x.clone().unwrap_or_default())),
            (Value::N(-3), Value::B(key.y.clone().unwrap_or_default())),
        ]);
        map.push((Value::U(0x01), cose_key));
    }

    if let Some(ref token) = response.pin_token {
        map.push((Value::U(0x02), Value::B(token.clone())));
    }

    if let Some(retries) = response.retries {
        map.push((Value::U(0x03), Value::U(retries as u64)));
    }

    if response.power_cycle_state {
        map.push((Value::U(0x04), Value::Bool(true)));
    }

    if let Some(uv_retries) = response.uv_retries {
        map.push((Value::U(0x05), Value::U(uv_retries as u64)));
    }

    cbor::encode(&Value::M(map))
}
